
server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: ${RABBIT_URL}
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

broker:
  queue:
    email:
      name: default.email